version: '2.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: tc-taas-zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
  kafka:
    image: wurstmeister/kafka
    container_name: tc-taas-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  esearch:
    image: elasticsearch:7.7.1
    container_name: tc-taas-es
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
  db:
    image: postgres
    container_name: tc-taas-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  kafka-client:
    build: ./kafka-client
    container_name: tc-taas-kafka-client
    extra_hosts:
      - "host.docker.internal:host-gateway"
  bus-api:
    container_name: tc-taas-bus-api
    build:
      context: ./generic-tc-service
      args:
        NODE_VERSION: 8.11.3
        GIT_URL: https://github.com/topcoder-platform/tc-bus-api
        GIT_BRANCH: dev
        BYPASS_TOKEN_VALIDATION: 1
    command: start kafka-client
    expose:
      - "3000"
    ports:
      - "8002:3000"
    depends_on:
      - kafka-client
    environment:
      - PORT=3000
      - KAFKA_URL=http://host.docker.internal:9092
      - JWT_TOKEN_SECRET=secret
      - VALID_ISSUERS="[\"https:\/\/topcoder-newauth.auth0.com\/\",\"https:\/\/api.topcoder-dev.com\",\"https:\/\/topcoder-dev.auth0.com\/\"]"
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_URL
      - AUTH0_AUDIENCE
      - AUTH0_PROXY_SERVER_URL
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
  es-processor:
    container_name: tc-taas-es-processor
    build:
      context: ./generic-tc-service
      args:
        NODE_VERSION: 12
        GIT_URL: https://github.com/topcoder-platform/taas-es-processor
        GIT_BRANCH: dev
        BYPASS_TOKEN_VALIDATION: 0
    command: start kafka-client
    depends_on:
      - kafka-client
    expose:
      - "3001"
    ports:
      - "5000:3001"
    environment:
      - PORT=3001
      - KAFKA_URL=http://host.docker.internal:9092
      - ES_HOST=http://host.docker.internal:9200
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_URL
      - AUTH0_AUDIENCE
      - AUTH0_PROXY_SERVER_URL
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
